/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define BOARD_XTAL0_CLK_HZ                         12000000U  /*!< Board xtal0 frequency in Hz */
#define BOARD_XTAL32K_CLK_HZ                          32768U  /*!< Board xtal32K frequency in Hz */

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************** Configuration BOARD_BootClockFRO12M **********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockFRO12M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKFRO12M_CORE_CLOCK   12000000U    /*!< Core clock frequency:12000000Hz */


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKFRO12M_ADC_CLOCK               0UL
#define BOARD_BOOTCLOCKFRO12M_ARMTRACE_CLOCK          0UL
#define BOARD_BOOTCLOCKFRO12M_ASYNCAPB_CLOCK          0UL
#define BOARD_BOOTCLOCKFRO12M_AUDPLL_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_CLKOUT_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_DMIC_CLOCK              0UL
#define BOARD_BOOTCLOCKFRO12M_EMC_CLOCK               0UL
#define BOARD_BOOTCLOCKFRO12M_FRG_CLOCK               0UL
#define BOARD_BOOTCLOCKFRO12M_FRO12M_CLOCK            12000000UL
#define BOARD_BOOTCLOCKFRO12M_FROHF_CLOCK             48000000UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM0_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM1_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM2_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM3_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM4_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM5_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM6_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM7_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM8_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOM9_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_FXCOMS_CLK32K_CLOCK     0UL
#define BOARD_BOOTCLOCKFRO12M_MAIN_CLOCK              12000000UL
#define BOARD_BOOTCLOCKFRO12M_MASTER_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_SC0_CLOCK               0UL
#define BOARD_BOOTCLOCKFRO12M_SC1_CLOCK               0UL
#define BOARD_BOOTCLOCKFRO12M_SCT_CLOCK               0UL
#define BOARD_BOOTCLOCKFRO12M_SDIO_CLOCK              0UL
#define BOARD_BOOTCLOCKFRO12M_SPIFI_CLOCK             0UL
#define BOARD_BOOTCLOCKFRO12M_SYSPLL_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_SYSTICK_CLOCK           0UL
#define BOARD_BOOTCLOCKFRO12M_SYSTEM_CLOCK            12000000UL
#define BOARD_BOOTCLOCKFRO12M_USB0_CLOCK              0UL
#define BOARD_BOOTCLOCKFRO12M_USB1_CLOCK              0UL
#define BOARD_BOOTCLOCKFRO12M_USBPLL_CLOCK            0UL
#define BOARD_BOOTCLOCKFRO12M_WDT_CLOCK               0UL

/*******************************************************************************
 * API for BOARD_BootClockFRO12M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockFRO12M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************* Configuration BOARD_BootClockFROHF48M *********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockFROHF48M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKFROHF48M_CORE_CLOCK   48000000U    /*!< Core clock frequency:48000000Hz */


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKFROHF48M_ADC_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF48M_ARMTRACE_CLOCK        0UL
#define BOARD_BOOTCLOCKFROHF48M_ASYNCAPB_CLOCK        0UL
#define BOARD_BOOTCLOCKFROHF48M_AUDPLL_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_CLKOUT_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_DMIC_CLOCK            0UL
#define BOARD_BOOTCLOCKFROHF48M_EMC_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF48M_FRG_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF48M_FRO12M_CLOCK          12000000UL
#define BOARD_BOOTCLOCKFROHF48M_FROHF_CLOCK           48000000UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM0_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM1_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM2_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM3_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM4_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM5_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM6_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM7_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM8_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOM9_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_FXCOMS_CLK32K_CLOCK   0UL
#define BOARD_BOOTCLOCKFROHF48M_MAIN_CLOCK            48000000UL
#define BOARD_BOOTCLOCKFROHF48M_MASTER_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_SC0_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF48M_SC1_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF48M_SCT_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF48M_SDIO_CLOCK            0UL
#define BOARD_BOOTCLOCKFROHF48M_SPIFI_CLOCK           0UL
#define BOARD_BOOTCLOCKFROHF48M_SYSPLL_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_SYSTICK_CLOCK         0UL
#define BOARD_BOOTCLOCKFROHF48M_SYSTEM_CLOCK          48000000UL
#define BOARD_BOOTCLOCKFROHF48M_USB0_CLOCK            0UL
#define BOARD_BOOTCLOCKFROHF48M_USB1_CLOCK            0UL
#define BOARD_BOOTCLOCKFROHF48M_USBPLL_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF48M_WDT_CLOCK             0UL

/*******************************************************************************
 * API for BOARD_BootClockFROHF48M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockFROHF48M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************* Configuration BOARD_BootClockFROHF96M *********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockFROHF96M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKFROHF96M_CORE_CLOCK   96000000U    /*!< Core clock frequency:96000000Hz */


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKFROHF96M_ADC_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF96M_ARMTRACE_CLOCK        0UL
#define BOARD_BOOTCLOCKFROHF96M_ASYNCAPB_CLOCK        0UL
#define BOARD_BOOTCLOCKFROHF96M_AUDPLL_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_CLKOUT_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_DMIC_CLOCK            0UL
#define BOARD_BOOTCLOCKFROHF96M_EMC_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF96M_FRG_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF96M_FRO12M_CLOCK          12000000UL
#define BOARD_BOOTCLOCKFROHF96M_FROHF_CLOCK           96000000UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM0_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM1_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM2_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM3_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM4_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM5_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM6_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM7_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM8_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOM9_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_FXCOMS_CLK32K_CLOCK   0UL
#define BOARD_BOOTCLOCKFROHF96M_MAIN_CLOCK            96000000UL
#define BOARD_BOOTCLOCKFROHF96M_MASTER_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_SC0_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF96M_SC1_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF96M_SCT_CLOCK             0UL
#define BOARD_BOOTCLOCKFROHF96M_SDIO_CLOCK            0UL
#define BOARD_BOOTCLOCKFROHF96M_SPIFI_CLOCK           0UL
#define BOARD_BOOTCLOCKFROHF96M_SYSPLL_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_SYSTICK_CLOCK         0UL
#define BOARD_BOOTCLOCKFROHF96M_SYSTEM_CLOCK          96000000UL
#define BOARD_BOOTCLOCKFROHF96M_USB0_CLOCK            0UL
#define BOARD_BOOTCLOCKFROHF96M_USB1_CLOCK            0UL
#define BOARD_BOOTCLOCKFROHF96M_USBPLL_CLOCK          0UL
#define BOARD_BOOTCLOCKFROHF96M_WDT_CLOCK             0UL

/*******************************************************************************
 * API for BOARD_BootClockFROHF96M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockFROHF96M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************** Configuration BOARD_BootClockPLL180M *********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockPLL180M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKPLL180M_CORE_CLOCK   180000000U    /*!< Core clock frequency:180000000Hz */


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKPLL180M_ADC_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL180M_ARMTRACE_CLOCK         0UL
#define BOARD_BOOTCLOCKPLL180M_ASYNCAPB_CLOCK         0UL
#define BOARD_BOOTCLOCKPLL180M_AUDPLL_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL180M_CLKOUT_CLOCK           1000000UL
#define BOARD_BOOTCLOCKPLL180M_DMIC_CLOCK             0UL
#define BOARD_BOOTCLOCKPLL180M_EMC_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL180M_FRG_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL180M_FRO12M_CLOCK           12000000UL
#define BOARD_BOOTCLOCKPLL180M_FROHF_CLOCK            48000000UL
#define BOARD_BOOTCLOCKPLL180M_FXCOM0_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL180M_FXCOM1_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL180M_FXCOM2_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL180M_FXCOM3_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL180M_FXCOM4_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL180M_FXCOM5_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL180M_FXCOM6_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL180M_FXCOM7_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL180M_FXCOM8_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL180M_FXCOM9_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL180M_FXCOMS_CLK32K_CLOCK    0UL
#define BOARD_BOOTCLOCKPLL180M_MAIN_CLOCK             180000000UL
#define BOARD_BOOTCLOCKPLL180M_MASTER_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL180M_SC0_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL180M_SC1_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL180M_SCT_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL180M_SDIO_CLOCK             0UL
#define BOARD_BOOTCLOCKPLL180M_SPIFI_CLOCK            0UL
#define BOARD_BOOTCLOCKPLL180M_SYSPLL_CLOCK           180000000UL
#define BOARD_BOOTCLOCKPLL180M_SYSTICK_CLOCK          0UL
#define BOARD_BOOTCLOCKPLL180M_SYSTEM_CLOCK           180000000UL
#define BOARD_BOOTCLOCKPLL180M_USB0_CLOCK             0UL
#define BOARD_BOOTCLOCKPLL180M_USB1_CLOCK             0UL
#define BOARD_BOOTCLOCKPLL180M_USBPLL_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL180M_WDT_CLOCK              0UL

/*******************************************************************************
 * API for BOARD_BootClockPLL180M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockPLL180M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ******************** Configuration BOARD_BootClockPLL220M *********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockPLL220M configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKPLL220M_CORE_CLOCK   110000000U    /*!< Core clock frequency:110000000Hz */


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKPLL220M_ADC_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL220M_ARMTRACE_CLOCK         0UL
#define BOARD_BOOTCLOCKPLL220M_ASYNCAPB_CLOCK         0UL
#define BOARD_BOOTCLOCKPLL220M_AUDPLL_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL220M_CLKOUT_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL220M_DMIC_CLOCK             0UL
#define BOARD_BOOTCLOCKPLL220M_EMC_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL220M_FRG_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL220M_FRO12M_CLOCK           12000000UL
#define BOARD_BOOTCLOCKPLL220M_FROHF_CLOCK            96000000UL
#define BOARD_BOOTCLOCKPLL220M_FXCOM0_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL220M_FXCOM1_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL220M_FXCOM2_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL220M_FXCOM3_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL220M_FXCOM4_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL220M_FXCOM5_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL220M_FXCOM6_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL220M_FXCOM7_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL220M_FXCOM8_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL220M_FXCOM9_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL220M_FXCOMS_CLK32K_CLOCK    0UL
#define BOARD_BOOTCLOCKPLL220M_MAIN_CLOCK             220000000UL
#define BOARD_BOOTCLOCKPLL220M_MASTER_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL220M_SC0_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL220M_SC1_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL220M_SCT_CLOCK              0UL
#define BOARD_BOOTCLOCKPLL220M_SDIO_CLOCK             0UL
#define BOARD_BOOTCLOCKPLL220M_SPIFI_CLOCK            0UL
#define BOARD_BOOTCLOCKPLL220M_SYSPLL_CLOCK           220000000UL
#define BOARD_BOOTCLOCKPLL220M_SYSTICK_CLOCK          0UL
#define BOARD_BOOTCLOCKPLL220M_SYSTEM_CLOCK           110000000UL
#define BOARD_BOOTCLOCKPLL220M_USB0_CLOCK             48000000UL
#define BOARD_BOOTCLOCKPLL220M_USB1_CLOCK             0UL
#define BOARD_BOOTCLOCKPLL220M_USBPLL_CLOCK           0UL
#define BOARD_BOOTCLOCKPLL220M_WDT_CLOCK              0UL

/*******************************************************************************
 * API for BOARD_BootClockPLL220M configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockPLL220M(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

